// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import frc.robot.subsystems.LEDsubsystem;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.*;
import com.ctre.phoenix.led.CANdle.*;

import edu.wpi.first.wpilibj2.command.Command;

/** An example command that uses an example subsystem. */
public class LEDcommand extends Command {
  @SuppressWarnings({"PMD.UnusedPrivateField", "PMD.SingularField"})
  private LEDsubsystem m_LEDsubsystem;
  private CANdle candle;
  private CANdleConfiguration config;
  private ErrorCode error; // gets the last error generated by the CANdle
  private CANdleFaults faults;

  private RainbowAnimation rainbowAnim;

  /**
   * Creates a new ExampleCommand.
   *
   * @param subsystem The subsystem used by this command.
   */
  public LEDcommand(LEDsubsystem subsystem) {
    m_LEDsubsystem = subsystem;
    // Use addRequirements() here to declare subsystem dependencies.

    config.stripType = LEDStripType.RGB; // set the strip type to RGB
    config.brightnessScalar = 0.5; // dim the LEDs to half brightness
    candle.configAllSettings(config);

    candle = new CANdle(5);
    config = new CANdleConfiguration();
    error = candle.getLastError();
    faults = new CANdleFaults();

    rainbowAnim = new RainbowAnimation(1, 0.5, 64);

    addRequirements(subsystem);
  }

  // Called when the command is initially scheduled.
  @Override
  public void initialize() {}

  // Called every time the scheduler runs while the command is scheduled.
  @Override
  public void execute() {
    candle.setLEDs(255, 255, 255);
    candle.animate(rainbowAnim);
  }
     
  // Called once the command ends or is interrupted.
  @Override
  public void end(boolean interrupted) {}

  // Returns true when the command should end.
  @Override
  public boolean isFinished() {
    return false;
  }
}
